# Generated by Django 4.2.11 on 2024-03-21 11:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_is_parent_alter_customuser_user_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_hash',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
